<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="MiPrimerServicio" targetNamespace="http://mod1lab4.javaarq.cibertec.edu.pe/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://mod1lab4.javaarq.cibertec.edu.pe/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<xs:schema elementFormDefault="unqualified" targetNamespace="http://mod1lab4.javaarq.cibertec.edu.pe/" version="1.0" xmlns:tns="http://mod1lab4.javaarq.cibertec.edu.pe/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="hola" type="tns:hola"/>
<xs:element name="holaResponse" type="tns:holaResponse"/>
<xs:complexType name="hola">
    <xs:sequence>
      <xs:element minOccurs="0" name="nombre" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="holaResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="holaResponse">
    <wsdl:part element="tns:holaResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="hola">
    <wsdl:part element="tns:hola" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="MiPrimerServicio">
    <wsdl:operation name="hola">
      <wsdl:input message="tns:hola" name="hola">
    </wsdl:input>
      <wsdl:output message="tns:holaResponse" name="holaResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MiPrimerServicioSoapBinding" type="tns:MiPrimerServicio">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="hola">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="hola">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="holaResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MiPrimerServicio">
    <wsdl:port binding="tns:MiPrimerServicioSoapBinding" name="MiPrimerServicioPort">
      <soap:address location="http://localhost:8080/mod1lab4/MiPrimerServicio"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>